// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ColumnList: typeof import('./src/components/ColumnList.vue')['default']
    DropDown: typeof import('./src/components/DropDown.vue')['default']
    DropDownItem: typeof import('./src/components/DropDownItem.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GlobalHeader: typeof import('./src/components/GlobalHeader.vue')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    Message: typeof import('./src/components/Message.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    PostList: typeof import('./src/components/PostList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Swiper: typeof import('./src/components/Swiper.vue')['default']
    Uploader: typeof import('./src/components/Uploader.vue')['default']
    UserProfile: typeof import('./src/components/UserProfile.vue')['default']
    ValidateForm: typeof import('./src/components/ValidateForm.vue')['default']
    ValidateInput: typeof import('./src/components/ValidateInput.vue')['default']
  }
}
